name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: oasdiff --help
      - name: asdf_plugin_test_1_10_23
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: oasdiff --version
          version: 1.10.23
